# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
OPSD (On-Policy Self-Distillation) Configuration.

Hint-Guided OPSD with Self-Evolving Navigator:
  - Single model plays three roles: Student, Teacher, Navigator
  - Navigator extracts hints from large model trajectories
  - Teacher uses hints to provide dense token-level guidance to Student via self-distillation
  - Navigator evolves via GRPO with binary rewards from Teacher trajectory correctness
  - Curriculum learning gradually drops ground-truth answers from Teacher conditioning
"""

from dataclasses import dataclass, field
from typing import Optional

from ..utils.py_functional import get_abs_path


@dataclass
class OPSDConfig:
    """Configuration for Hint-Guided On-Policy Self-Distillation."""

    # === Navigator ===
    num_hints: int = 4
    """K: number of hints per question generated by Navigator."""
    navigator_response_length: int = 512
    """Max token length for Navigator hint generation."""
    navigator_prompt_template: Optional[str] = None
    """Path to Jinja template for Navigator prompt."""
    navigator_include_student_trajectory: bool = False
    """Whether to pass the current student rollout text into Navigator prompts.

    Default False preserves the existing behavior where Navigator only sees the
    question and reference trajectory. When enabled, templates can additionally
    use the `student_trajectory` variable.
    """
    navigator_max_trajectory_length: Optional[int] = None
    """Max token length for trajectory-like text consumed by Navigator.

    If None, falls back to `max_trajectory_length` for backward compatibility.
    """
    teacher_max_trajectory_length: Optional[int] = None
    """Max token length for trajectory-like text consumed by Teacher-side prompts.

    This applies to self-distill trajectory hints, fallback trajectory prompts,
    SDPO selected candidate texts, and similar teacher-context fields.
    If None, falls back to `max_trajectory_length` for backward compatibility.
    """
    max_trajectory_length: int = 4096
    """Legacy shared trajectory truncation length.

    Kept for backward compatibility. If the new Navigator/Teacher-specific fields
    are unset, both default to this value.
    """
    student_rollout_n: int = 1
    """Number of on-policy student rollouts sampled per prompt in OPSD.

    Default 1 keeps existing behavior. When > 1, each sampled student trajectory
    is expanded into the same downstream OPSD loss pipeline.
    """
    dynamic_sample_hint: bool = False
    """Enable dynamic hint selection for reasoner training.

    When enabled, Teacher samples multiple rollouts per hint, Navigator reward is
    the mean accuracy of each hint's rollout group, and Reasoner training uses
    only the dynamically selected best hint group per question.
    """
    teacher_rollout_n: int = 1
    """Number of Teacher rollouts sampled per hint when dynamic_sample_hint is enabled."""

    # === Teacher ===
    teacher_hint_template: Optional[str] = None
    """Path to Jinja template for injecting hint into Teacher prompt."""
    sdpo_teacher_template: Optional[str] = None
    """Path to Jinja template for SDPO teacher prompt construction."""
    teacher_context_mode: str = "hint"
    """Teacher-side extra context mode for regular OPSD teacher prompts.

    - hint: existing behavior, Teacher sees question + hint (+ optional GT).
    - hint_plus_core_trajectories: Teacher additionally sees compact reference
      and student trajectory snippets alongside the Navigator feedback.
    - reference_and_student_trajectories: Teacher sees the reference and student
      trajectories directly; templates may ignore `hint`.
    """
    teacher_reference_context_length: Optional[int] = None
    """Max token length for reference trajectory text passed to Teacher prompts.

    If None, falls back to `teacher_max_trajectory_length`.
    """
    teacher_student_context_length: Optional[int] = None
    """Max token length for student trajectory text passed to Teacher prompts.

    If None, falls back to `teacher_max_trajectory_length`.
    """

    # === OPSD Loss ===
    alpha: float = 0.5
    """Weight for on-policy loss vs off-policy loss: L_rea = alpha * L_on + (1 - alpha) * L_off."""
    lambda_nav: float = 0.1
    """Navigator GRPO loss weight: L = L_rea + lambda_nav * L_nav."""
    distillation_loss_type: str = "kl"
    """Distillation divergence for OPSD: kl | jsd."""
    opsd_kl_penalty: str = "kl"
    """KL penalty variant when distillation_loss_type=kl: kl | abs | mse | low_var_kl | full."""

    # === Top-k KL Approximation (ref: SDPO) ===
    distillation_topk: Optional[int] = None
    """Top-k logits for KL approximation. None = full vocabulary KL."""
    distillation_topk_source: str = "teacher"
    """Which model defines the top-k support set when distillation_topk is enabled.

    - teacher: current default, use teacher top-k tokens
    - student: use student top-k tokens, then gather teacher probabilities on the
      same support set
    """
    distillation_add_tail: bool = True
    """Include tail probability mass in top-k KL computation."""
    distill_token_selection: str = "all"
    """Token selection strategy for distillation targets.

    - all: use every valid response token
    - low_teacher_entropy: only distill the lowest-entropy teacher tokens
    - high_teacher_student_gap: only distill the tokens where teacher/student
      token distributions differ the most
    """
    distill_token_keep_ratio: float = 1.0
    """Fraction of valid response tokens kept for distillation under token selection."""
    outcome_ppo_coef: float = 0.0
    """Extra PPO-style outcome loss weight for self-distill baseline.

    When > 0, the use_gt_as_hint=True branch adds a student-side PPO loss using
    the reward function's token-level scores (accuracy/format/length).
    """
    outcome_ppo_incorrect_only: bool = False
    """If True, split self-distill supervision by correctness.

    Correct samples use only OPSD distillation loss.
    Incorrect samples use only outcome PPO loss.
    """
    freeze_teacher_model: bool = False
    """If True, use the frozen reference policy as the Teacher scorer in OPSD.

    This freezes the Teacher distribution used for on/off-policy distillation so it
    does not drift with Student updates. Teacher rollout generation is unchanged.
    """
    enable_grpo_opsd_simple: bool = False
    """Enable a separate simple GRPO+RLSD mode.

    This mode skips Navigator entirely and injects Teacher guidance by
    reweighting token-level advantages on the sampled Student trajectory.
    """
    rlsd_lambda: float = 0.5
    """Mixing weight between base advantage and RLSD reweighted advantage."""
    rlsd_reweight_clip_range: Optional[float] = None
    """Clip range for RLSD evidence weights.

    If None, defaults to the PPO/GRPO clip ratio low value (typically 0.2).
    """
    rlsd_teacher_sync_interval: int = 0
    """Sync teacher weights from actor every N training steps.

    0 = no periodic sync (default behavior: frozen teacher stays frozen,
    non-frozen teacher shares actor weights and updates every micro-batch).
    When > 0, requires freeze_teacher_model=True. The teacher starts as a
    frozen copy and gets refreshed from actor weights every N steps.
    This provides a middle ground between fully frozen (stale signal)
    and fully shared (unstable / distribution drift).
    """
    rlsd_thought_only: bool = False
    """Only apply RLSD reweighting within <thought>...</thought> spans.

    When True, tokens outside the thought span (format tags, answer content, etc.)
    keep their original advantages (pure GRPO), and only the reasoning tokens
    inside <thought>...</thought> get teacher-guided credit redistribution.
    """
    rlsd_negative_only: bool = False
    """Only apply RLSD reweighting on negative-advantage (incorrect) samples.

    When True, sequences with A > 0 keep their original advantages (pure GRPO),
    and only sequences with A < 0 get teacher-guided blame redistribution.
    This avoids the response-length collapse caused by under-reinforcing
    reasoning tokens in correct responses.
    """
    rlsd_lambda_warmup_steps: int = 0
    """Steps over which rlsd_lambda linearly warms up from 0 to its target value.

    0 = no warmup, use rlsd_lambda from the start.
    When > 0, effective_lambda ramps from 0 to rlsd_lambda over this many steps.
    This allows the model to learn format with pure GRPO first before RLSD kicks in.
    """
    rlsd_lambda_decay_steps: int = 0
    """Steps over which rlsd_lambda linearly decays from its target value to 0.

    0 = no decay, keep rlsd_lambda after warmup.
    When > 0, decay begins after warmup completes and takes this many steps to reach 0.
    The full schedule is: warmup → hold at peak → decay to 0.
    """
    stgca_lambda: Optional[float] = None
    """Deprecated alias for rlsd_lambda."""
    stgca_reweight_clip_range: Optional[float] = None
    """Deprecated alias for rlsd_reweight_clip_range."""
    stgca_teacher_sync_interval: Optional[int] = None
    """Deprecated alias for rlsd_teacher_sync_interval."""
    stgca_thought_only: Optional[bool] = None
    """Deprecated alias for rlsd_thought_only."""
    stgca_negative_only: Optional[bool] = None
    """Deprecated alias for rlsd_negative_only."""
    stgca_lambda_warmup_steps: Optional[int] = None
    """Deprecated alias for rlsd_lambda_warmup_steps."""
    stgca_lambda_decay_steps: Optional[int] = None
    """Deprecated alias for rlsd_lambda_decay_steps."""
    enable_sdpo: bool = False
    """Enable a separate SDPO self-distillation mode.

    This mode samples multiple student candidates, selects the shortest correct
    and shortest incorrect trajectories as teacher-side context, then performs
    a separate on-policy distillation rollout.
    """
    sdpo_num_candidates: int = 8
    """Number of candidate student rollouts per prompt used to build SDPO teacher context."""

    # === Curriculum Learning ===
    curriculum_warmup_steps: int = 100
    """T_warmup: steps over which ground-truth drop probability linearly increases from 0 to 1."""

    off_policy_include_gt_answer: bool = True
    """Whether Teacher rollout prompt includes GT answer in full/static OPSD path.

    True (default): keep existing behavior (Teacher sees hint + GT when generating
    off-policy trajectories).
    False: Teacher rollout uses hint only, reducing potential answer leakage into
    off-policy distillation targets.
    """

    # === Self-Distilled Reasoner Mode ===
    use_gt_as_hint: bool = False
    """Skip Navigator rollout entirely and use ground-truth answers as hints.
    This implements the 'Self-Distilled Reasoner' baseline:
      - No Navigator rollout or training
      - Teacher is conditioned on GT answer (p_drop forced to 0)
      - On-policy KL(Teacher || Student) distillation only
    When True, num_hints is forced to 1 and lambda_nav is forced to 0."""
    self_distill_negative_off_policy: bool = False
    """Enable a negative off-policy loss only in the use_gt_as_hint=True branch.

    When enabled, the self-distill path additionally samples one Teacher rollout
    under the reference-trajectory-conditioned Teacher prompt and applies a
    reverse-sign off-policy divergence so Student is pushed away from that
    reference-conditioned output distribution.

    For stability, this mode is only supported with JSD-based distillation.
    """
    self_distill_negative_off_policy_coef: float = 0.1
    """Weight for the negative off-policy term in self-distill mode."""
    self_distill_mask_prefix_tokens: int = 0
    """Mask the first N valid student response tokens from self-distill loss.

    This only applies in the use_gt_as_hint=True branch and only affects the
    distillation mask, not rollout generation or reward computation.
    """

    # === Navigator GRPO ===
    nav_clip_ratio_low: float = 0.2
    """Lower clip range for Navigator GRPO policy loss."""
    nav_clip_ratio_high: float = 0.28
    """Higher clip range for Navigator GRPO policy loss."""
    nav_clip_ratio_dual: float = 5.0
    """Dual clip range for Navigator GRPO policy loss."""

    def _resolve_deprecated_alias(self, *, new_name: str, old_name: str):
        new_value = getattr(self, new_name)
        old_value = getattr(self, old_name)
        if old_value is not None:
            default_value = OPSDConfig.__dataclass_fields__[new_name].default
            if new_value != default_value and new_value != old_value:
                raise ValueError(
                    f"Both opsd.{new_name} and deprecated opsd.{old_name} were set "
                    f"with different values: {new_value} != {old_value}."
                )
            new_value = old_value
        setattr(self, new_name, new_value)
        setattr(self, old_name, new_value)

    def _resolve_rlsd_aliases(self):
        alias_pairs = (
            ("rlsd_lambda", "stgca_lambda"),
            ("rlsd_reweight_clip_range", "stgca_reweight_clip_range"),
            ("rlsd_teacher_sync_interval", "stgca_teacher_sync_interval"),
            ("rlsd_thought_only", "stgca_thought_only"),
            ("rlsd_negative_only", "stgca_negative_only"),
            ("rlsd_lambda_warmup_steps", "stgca_lambda_warmup_steps"),
            ("rlsd_lambda_decay_steps", "stgca_lambda_decay_steps"),
        )
        for new_name, old_name in alias_pairs:
            self._resolve_deprecated_alias(new_name=new_name, old_name=old_name)

    def post_init(self):
        self._resolve_rlsd_aliases()

        if self.distillation_loss_type not in {"kl", "jsd"}:
            raise ValueError(
                f"Unknown distillation_loss_type={self.distillation_loss_type}. Expected one of: kl, jsd."
            )
        if self.distill_token_selection not in {
            "all",
            "low_teacher_entropy",
            "high_teacher_student_gap",
        }:
            raise ValueError(
                "Unknown opsd.distill_token_selection="
                f"{self.distill_token_selection}. Expected one of: "
                "all, low_teacher_entropy, high_teacher_student_gap."
            )
        if self.distillation_topk_source not in {"teacher", "student"}:
            raise ValueError(
                "Unknown opsd.distillation_topk_source="
                f"{self.distillation_topk_source}. Expected one of: teacher, student."
            )
        if not (0.0 < self.distill_token_keep_ratio <= 1.0):
            raise ValueError(
                "opsd.distill_token_keep_ratio must be in (0, 1], "
                f"got {self.distill_token_keep_ratio}."
            )
        if self.teacher_context_mode not in {
            "hint",
            "hint_plus_core_trajectories",
            "reference_and_student_trajectories",
        }:
            raise ValueError(
                "Unknown opsd.teacher_context_mode="
                f"{self.teacher_context_mode}. Expected one of: "
                "hint, hint_plus_core_trajectories, reference_and_student_trajectories."
            )
        if self.student_rollout_n < 1:
            raise ValueError(
                f"opsd.student_rollout_n must be >= 1, got {self.student_rollout_n}."
            )
        if self.teacher_rollout_n < 1:
            raise ValueError(
                f"opsd.teacher_rollout_n must be >= 1, got {self.teacher_rollout_n}."
            )
        if not self.dynamic_sample_hint and self.teacher_rollout_n != 1:
            raise ValueError(
                "opsd.teacher_rollout_n > 1 requires opsd.dynamic_sample_hint=True."
            )
        if self.dynamic_sample_hint and self.use_gt_as_hint:
            raise ValueError(
                "opsd.dynamic_sample_hint is not supported when opsd.use_gt_as_hint=True."
            )
        if self.dynamic_sample_hint and self.enable_sdpo:
            raise ValueError(
                "opsd.dynamic_sample_hint is not supported when opsd.enable_sdpo=True."
            )
        if self.self_distill_negative_off_policy and not self.use_gt_as_hint:
            raise ValueError(
                "opsd.self_distill_negative_off_policy only supports opsd.use_gt_as_hint=True."
            )
        if self.self_distill_negative_off_policy and self.enable_sdpo:
            raise ValueError(
                "opsd.self_distill_negative_off_policy is not supported with opsd.enable_sdpo=True."
            )
        if self.self_distill_negative_off_policy and self.distillation_loss_type != "jsd":
            raise ValueError(
                "opsd.self_distill_negative_off_policy requires opsd.distillation_loss_type=jsd. "
                "Negative KL is numerically unstable and is intentionally disallowed."
            )
        if self.self_distill_negative_off_policy_coef < 0:
            raise ValueError(
                "opsd.self_distill_negative_off_policy_coef must be >= 0, "
                f"got {self.self_distill_negative_off_policy_coef}."
            )
        if self.self_distill_mask_prefix_tokens < 0:
            raise ValueError(
                "opsd.self_distill_mask_prefix_tokens must be >= 0, "
                f"got {self.self_distill_mask_prefix_tokens}."
            )
        if self.stgca_teacher_sync_interval < 0:
            raise ValueError(
                "opsd.rlsd_teacher_sync_interval must be >= 0, "
                f"got {self.stgca_teacher_sync_interval}."
            )
        if self.stgca_teacher_sync_interval > 0 and not self.freeze_teacher_model:
            raise ValueError(
                "opsd.rlsd_teacher_sync_interval > 0 requires opsd.freeze_teacher_model=True "
                "so that a separate teacher module exists for periodic syncing."
            )
        if not (0.0 <= self.stgca_lambda <= 1.0):
            raise ValueError(
                f"opsd.rlsd_lambda must be in [0, 1], got {self.stgca_lambda}."
            )
        if self.stgca_reweight_clip_range is not None and self.stgca_reweight_clip_range < 0:
            raise ValueError(
                "opsd.rlsd_reweight_clip_range must be >= 0 when set, "
                f"got {self.stgca_reweight_clip_range}."
            )
        if self.stgca_lambda_warmup_steps < 0:
            raise ValueError(
                "opsd.rlsd_lambda_warmup_steps must be >= 0, "
                f"got {self.stgca_lambda_warmup_steps}."
            )
        if self.stgca_lambda_decay_steps < 0:
            raise ValueError(
                "opsd.rlsd_lambda_decay_steps must be >= 0, "
                f"got {self.stgca_lambda_decay_steps}."
            )
        if self.navigator_max_trajectory_length is None:
            self.navigator_max_trajectory_length = self.max_trajectory_length
        if self.teacher_max_trajectory_length is None:
            self.teacher_max_trajectory_length = self.max_trajectory_length
        if self.teacher_reference_context_length is None:
            self.teacher_reference_context_length = self.teacher_max_trajectory_length
        if self.teacher_student_context_length is None:
            self.teacher_student_context_length = self.teacher_max_trajectory_length
        self.navigator_prompt_template = get_abs_path(
            self.navigator_prompt_template, prompt="Navigator prompt template"
        )
        self.teacher_hint_template = get_abs_path(
            self.teacher_hint_template, prompt="Teacher hint template"
        )
        self.sdpo_teacher_template = get_abs_path(
            self.sdpo_teacher_template, prompt="SDPO teacher prompt template"
        )
